"""E2E harness fixtures. No top-level `playwright` import: this module must stay importable
even when the `e2e` extra is not installed.

Also generates `e2e/RESULTS.md` after every run (gitignored) — one row per test, carrying its
`[qa:<feature>:<case-id>]` tag, the case's priority from `e2e/plans/<feature>.plan.yaml`, and the
outcome. A run only replaces the rows for the tests it actually ran, per `e2e-authoring.md`.
"""

import datetime
import os
import re
import urllib.request
from pathlib import Path
from urllib.error import URLError

import pytest

E2E_BASE_URL = os.environ.get("ADMIN_ERRORS_E2E_BASE_URL", "http://127.0.0.1:8000")
_E2E_DIR = Path(__file__).parent
_QA_TAG_RE = re.compile(r"\[qa:([\w-]+):([\w-]+)\]\s*(.*)")


def ready_url() -> str:
    return f"{E2E_BASE_URL}/admin/login/"


@pytest.fixture(scope="session")
def server_available() -> None:
    try:
        urllib.request.urlopen(ready_url(), timeout=2)
    except (URLError, OSError):
        pytest.skip(f"no demo server on {ready_url()}; run `make e2e-up` first")


@pytest.fixture(scope="session")
def base_url() -> str:
    return E2E_BASE_URL


def pytest_configure(config: pytest.Config) -> None:
    # Capture an artifact on failure at minimum (screenshots), and keep them out of the repo tree
    # the developer usually looks at. No-op when pytest-playwright is not installed.
    if hasattr(config.option, "screenshot"):
        config.option.screenshot = "only-on-failure"
    if hasattr(config.option, "output"):
        config.option.output = str(_E2E_DIR / "artifacts")


def pytest_collection_modifyitems(config: pytest.Config, items: list[pytest.Item]) -> None:
    config._qa_docstrings = {  # type: ignore[attr-defined]
        item.nodeid: getattr(getattr(item, "function", None), "__doc__", None) or ""
        for item in items
    }


def _plan_priority(feature: str, case_id: str) -> str:
    plan_path = _E2E_DIR / "plans" / f"{feature}.plan.yaml"
    if not plan_path.exists():
        return "-"
    match = re.search(
        rf"-\s*id:\s*{re.escape(case_id)}\s*\n\s*priority:\s*(\w+)", plan_path.read_text()
    )
    return match.group(1) if match else "-"


_RUN_OUTCOMES: dict[str, str] = {}


def pytest_runtest_logreport(report: pytest.TestReport) -> None:
    if report.when == "call" or (report.when == "setup" and report.outcome != "passed"):
        _RUN_OUTCOMES[report.nodeid] = report.outcome


def pytest_sessionfinish(session: pytest.Session, exitstatus: int) -> None:
    if not _RUN_OUTCOMES:
        return
    docstrings: dict[str, str] = getattr(session.config, "_qa_docstrings", {})
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    header = ["Test", "Plan case", "Priority", "Description", "Result", "Last run"]
    rows: dict[str, list[str]] = {}
    results_path = _E2E_DIR / "RESULTS.md"
    if results_path.exists():
        for line in results_path.read_text().splitlines():
            if not line.startswith("| ") or line.startswith("| Test") or line.startswith("|---"):
                continue
            cols = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cols) == len(header):
                rows[cols[0]] = cols

    for nodeid, outcome in _RUN_OUTCOMES.items():
        doc = docstrings.get(nodeid, "")
        tag_match = _QA_TAG_RE.search(doc)
        if tag_match:
            feature, case_id, description = tag_match.groups()
            plan_case = f"{feature}:{case_id}"
            priority = _plan_priority(feature, case_id)
        else:
            plan_case, priority = "-", "-"
            description = doc.strip().splitlines()[0] if doc.strip() else "-"
        result = {"passed": "PASS", "failed": "FAIL", "skipped": "SKIP"}.get(
            outcome, outcome.upper()
        )
        rows[nodeid] = [nodeid, plan_case, priority, description.strip(), result, now]

    lines = [
        "# e2e results",
        "",
        "Generated by `uv run --extra e2e pytest e2e -q`. Rows for tests not run this time keep "
        "their previous `Last run` value.",
        "",
        "| " + " | ".join(header) + " |",
        "|" + "|".join(["---"] * len(header)) + "|",
    ]
    for nodeid in sorted(rows):
        lines.append("| " + " | ".join(rows[nodeid]) + " |")
    results_path.write_text("\n".join(lines) + "\n")
