# Generated by Django 5.2.17 on 2026-09-15 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(max_length=40, unique=True, verbose_name="fingerprint"),
                ),
                (
                    "exception_type",
                    models.CharField(db_index=True, max_length=200, verbose_name="exception type"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="title")),
                ("culprit", models.CharField(blank=True, max_length=500, verbose_name="culprit")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="error",
                        max_length=10,
                        verbose_name="level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("first_seen", models.DateTimeField(verbose_name="first seen")),
                ("last_seen", models.DateTimeField(db_index=True, verbose_name="last seen")),
                ("count", models.PositiveBigIntegerField(default=0, verbose_name="count")),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="resolved at"),
                ),
                (
                    "notified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="notified at"),
                ),
                ("last_event", models.JSONField(blank=True, null=True, verbose_name="last event")),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="resolved by",
                    ),
                ),
            ],
            options={
                "verbose_name": "issue",
                "verbose_name_plural": "issues",
                "ordering": ["-last_seen"],
                "permissions": [
                    ("view_issue_context", "Can view request context and local variables")
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True, verbose_name="timestamp")),
                ("payload", models.JSONField(verbose_name="payload")),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="admin_errors.issue",
                        verbose_name="issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.CreateModel(
            name="IssueDailyCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("count", models.PositiveIntegerField(default=0, verbose_name="count")),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_counts",
                        to="admin_errors.issue",
                        verbose_name="issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "issue daily count",
                "verbose_name_plural": "issue daily counts",
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["status", "-last_seen"], name="ae_issue_status_seen_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["issue", "-timestamp"], name="ae_event_issue_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="issuedailycount",
            index=models.Index(fields=["date"], name="ae_daily_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="issuedailycount",
            constraint=models.UniqueConstraint(
                fields=("issue", "date"), name="ae_daily_issue_date_uniq"
            ),
        ),
    ]
